version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "clone-clean"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "sharp"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "clone-clean"
    schedule:
      interval: "weekly"
